Systematics = [
#  'nominal',
#  'Det1_down',
#  'Det1_up',
#  "Det2_down",
#  "Det2_up",
#  "Mix1_down",
#  "Mix1_up",
#  "Mix2_down",
#  "Mix2_up",
#  "Mix3_down",
#  "Mix3_up",
#  "Model1_down",
#  "Model1_up",
#  "Model2_down",
#  "Model2_up",
#  "Model3_down",
#  "Model3_up",
#  "Model4_down",
#  "Model4_up",
#  "Stat1_down",
#  "Stat1_up",
#  "Stat2_down",
#  "Stat2_up",
#  "Stat3_down",
#  "Stat3_up",
#  "Stat4_down",
#  "Stat4_up",
#  "Stat5_down",
#  "Stat5_up",
#  "Stat6_down",
#  "Stat6_up",
#  "EtaInt_down",
#  "EtaInt_up",
#  "EtaInt-highE_down",
#  "EtaInt-highE_up",
#  "EtaInt-negEta_down",
#  "EtaInt-negEta_up",
#  "EtaInt-posEta_down",
#  "EtaInt-posEta_up",
#  "EtaInt-totalStat_down",
#  "EtaInt-totalStat_up",
#  "FlavComp_down",
#  "FlavComp_up",
#  "FlavResp_down",
#  "FlavResp_up",
#  "MC_down",
#  "MC_up",
#  "NP1_down",
#  "NP1_up",
#  "NP2_down",
#  "NP2_up",
#  "NP3_down",
#  "NP3_up",
#  "NP4_down",
#  "NP4_up",
#  "NP5_down",
#  "NP5_up",
#  "NP6_down",
#  "NP6_up",
#  "NP7_down",
#  "NP7_up",
#  "NP8_down",
#  "NP8_up",
#  "NP9_down",
#  "NP9_up",
#  "NP10_down",
#  "NP10_up",
#  "NP11_down",
#  "NP11_up",
#  "NP12_down",
#  "NP12_up",
#  "PUMU_down",
#  "PUMU_up",
#  "PUNPV_down",
#  "PUNPV_up",
#  "PUPt_down",
#  "PUPt_up",
#  "PUrho_down",
#  "PUrho_up",
#  "punch_down",
#  "punch_up",
#  "single_down",
#  "single_up",
#  "BJES_down",
#  "BJES_up",
  "MET_SoftTrk_ResoPara",
  "MET_SoftTrk_ResoPerp",
  "MET_SoftTrk_Scale_down",
  "MET_SoftTrk_Scale_up",
  "EG_RESOLUTION_ALL_down",
  "EG_RESOLUTION_ALL_up",
  "EG_SCALE_ALL_down",
  "EG_SCALE_ALL_up",
]
